### ISSUE TITLE
Enhancement: custom module trees

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/software-stack#11]
While the CC CVMFS repos are great, I already have some cases where other modules are required. Hence it would be very nice to facilitate adding new modules with EasyBuild, and allowing the nodes to see the additional tree(s).

**Comment by ofisette** [comment]
This is a feature I would like too. The problem with `/opt/software/modulefiles` is that it does not reproduce the toolchain hierarchy. If I install a package manually and make a module there for it, that works fine, but if I used `eb` to install a cluster-specific package, its module would end up in a toolchain directory hierarchy, and will not be made available automatically when a compiler or MPI version is loaded. This would require toolchain modules to set `MODULEPATH` for this specific hierarchy in addition to our CVMFS and `~/.local/easybuild/modules` hierarchies. It could live in `/opt/easybuild/modules`.

**Comment by verdurin** [comment]
This may not be so necessary for your CC users, but for those of us elsewhere, it's not very clear which `easyconfigs` I can build given that you have a different scheme than the upstream default. As expected any of the upstream ones with e.g. `foss` toolchain don't build at least with the defaults.

For example, say I want to build `VEP`, with a `GCC`-type toolchain, is there an option?

**Comment by mboisson** [comment]
I'm not sure, but I think this specific case stems from the fact that VEP is installed with a full blown toolchain (foss) rather than GCCcore. I would think unlikely that perl modules requires MPI... I would try to bring all of those dependencies down to the GCCcore level.

**Comment by verdurin** [comment]
Okay, thanks. Will give that a try.

**Comment by mboisson** [comment]
As a potential implementation to make it possible to add MNS-aware localized module paths automatically, I wrote the following implementation a while ago : 

```
diff --git a/lmod/SitePackage.lua b/lmod/SitePackage.lua
index c41322b..1fbf83b 100644
--- a/lmod/SitePackage.lua
+++ b/lmod/SitePackage.lua
@@ -112,11 +112,13 @@ function dofile (filename)
 	return f()
 end

-dofile("/cvmfs/soft.computecanada.ca/config/lmod/SitePackage_logging.lua")
-dofile("/cvmfs/soft.computecanada.ca/config/lmod/SitePackage_licenses.lua")
-dofile("/cvmfs/soft.computecanada.ca/config/lmod/SitePackage_families.lua")
-dofile("/cvmfs/soft.computecanada.ca/config/lmod/SitePackage_properties.lua")
-dofile("/cvmfs/soft.computecanada.ca/config/lmod/SitePackage_visible.lua")
+local lmod_package_path = os.getenv("LMOD_PACKAGE_PATH")
+dofile(pathJoin(lmod_package_path,"SitePackage_logging.lua"))
+dofile(pathJoin(lmod_package_path,"SitePackage_licenses.lua"))
+dofile(pathJoin(lmod_package_path,"SitePackage_families.lua"))
+dofile(pathJoin(lmod_package_path,"SitePackage_properties.lua"))
+dofile(pathJoin(lmod_package_path,"SitePackage_visible.lua"))
+dofile(pathJoin(lmod_package_path,"SitePackage_localpaths.lua"))

 sandbox_registration{ loadfile = loadfile, assert = assert, loaded_modules = loaded_modules, serializeTbl = serializeTbl, clearWarningFlag = clearWarningFlag  }
 require("strict")
@@ -203,9 +205,11 @@ local function load_hook(t)
 	set_family(t)
 	default_module_change_warning(t)
 	log_module_load(t,true)
+	set_local_paths(t)
 end
 local function spider_hook(t)
 	set_props(t)
+	set_local_paths(t)
 end
 hook.register("load",           load_hook)
 hook.register("load_spider", 	spider_hook)
diff --git a/lmod/SitePackage_localpaths.lua b/lmod/SitePackage_localpaths.lua
new file mode 100644
index 0000000..3294160
--- /dev/null
+++ b/lmod/SitePackage_localpaths.lua
@@ -0,0 +1,59 @@
+require("serializeTbl")
+require("string_utils")
+
+function set_local_paths(t)
+
+	local localModulePaths = os.getenv("RSNT_LOCAL_MODULEPATHS") or nil
+	if localModulePaths == nil then
+		return
+	end
+
+
+	local moduleNamesToCheck = { "openmpi", "intelmpi", "gcc", "intel", "cuda" }
+	local myModuleName = myModuleName()
+
+	if has_value(moduleNamesToCheck, myModuleName) then
+		local arch = os.getenv("RSNT_ARCH")
+		local myModuleFullName = myModuleFullName()
+		local myFileName = myFileName()
+
+		-- get module version with two dots only
+		local myModuleVersion = myModuleVersion()
+		local myModuleVersionTwoDots = string.gsub(myModuleVersion, ".[0-9]*$", "")
+		local myModuleVersionOneDot = string.gsub(myModuleVersionTwoDots, ".[0-9]*$", "")
+
+		local rootModulePath = "^/cvmfs/soft.computecanada.ca/easybuild/modules/"
+		local relativeFileName = string.gsub(myFileName, rootModulePath, "")
+		-- from the module filename, remove the openmpi/<version>.lua
+		local relativeModulePath = string.gsub(relativeFileName, myModuleFullName .. ".lua", "")
+
+		local subPath = myModuleName .. myModuleVersionTwoDots
+		if myModuleName == "openmpi" or myModuleName == "intelmpi" or myModuleName == "impi" then
+			-- build the module path by changing Compiler or CUDA by MPI
+			relativeModulePath = string.gsub(relativeModulePath, "/Compiler/", "/MPI/")
+			relativeModulePath = string.gsub(relativeModulePath, "/CUDA/", "/MPI/")
+		elseif myModuleName == "gcc" or myModuleName == "intel" or myModuleName == "pgi" then
+			-- build the module path by changing Core by Compiler
+			relativeModulePath = string.gsub(relativeModulePath, "/Core/", "/Compiler/" .. arch)
+		elseif myModuleName == "cuda" then
+			-- build the module path by changing Compiler for CUDA
+			relativeModulePath = string.gsub(relativeModulePath, "/Compiler/", "/CUDA/")
+		end
+
+		-- intelmpi is a corner case in which we don't use the same convention
+		if myModuleName == "intelmpi" then
+			subPath = "impi" .. myModuleVersionTwoDots
+		end
+		-- and adding the subPath
+		relativeModulePath = pathJoin(relativeModulePath, subPath)
+
+		for localModulePathRoot in localModulePaths:split(":") do
+			local localModulePath = pathJoin(localModulePathRoot, relativeModulePath)
+			--LmodWarning(myModuleFullName .. ":" .. localModulePath)
+			if isDir(localModulePath) then
+				prepend_path("MODULEPATH", localModulePath)
+			end
+		end
+	end
+end
+
``` 

The idea would be that a site can specify the environment variable `RSNT_LOCAL_MODULEPATHS`  as a secondary root for modules (i.e. it would be the same as the module-path for EasyBuild). This would inject relevant code into the compiler/mpi/cuda modules to modify the module path, and adjust the spider and load module functions accordingly. 

If this is seems like a viable option, I can look at pushing this next week.

**Comment by ofisette** [comment]
`RSNT_LOCAL_MODULEPATHS` sounds great. Looking at the patch, I am wondering if `arch` should be in `moduleNamesToCheck`. I am not familiar with the LMod code, but loading an `arch` module should bring in local arch-specific modules, and I do not see how it happens with that patch. (I know I would have a mix of architectures in our local module path.)

**Comment by mboisson** [comment]
The architecture part would be taken care of due to the fact that we are replacing the root of the current module (aka `/cvmfs/soft.computecanada.ca/easybuild/modules`) by the local one. Everything else is relative to that, including the architecture.

**Comment by verdurin** [comment]
@mboisson yes, looks good.

The other part of this, as my earlier comments indicate, is documentation to assist with building modules for this local environment.

**Comment by mboisson** [comment]
For technical reasons, this is waiting for 
https://github.com/ComputeCanada/software-stack/issues/13
to be implemented (working on this today).

**Comment by mboisson** [comment]
I think I have made the required changes to support this. This is currently only on our "dev" CVMFS repository, and will not be pushed to production until further tested. 

In order to test with our dev repository, you can use `proot` : 
`/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/proot -b /cvmfs/soft-dev.computecanada.ca:/cvmfs/soft.computecanada.ca env -i CC_CLUSTER=$CC_CLUSTER TERM=$TERM HOME=$HOME bash -l` 

This will start a new shell in which all file access to `/cvmfs/soft.computecanada.ca` will be replaced by `/cvmfs/soft-dev.computecanada.ca`. For this, you need to also mount our `dev` repository. You will need to modify your
`/etc/cvmfs/default.local` to include it : 
`CVMFS_REPOSITORIES="cvmfs-config.computecanada.ca,soft.computecanada.ca,soft-dev.computecanada.ca"` 

Once this is done, you should be able to install a recipe locally, for example : 
```
eb --force --installpath /opt/software/easybuild SCOTCH-6.0.9-gompi-2020a.eb
``` 
and have the module it generates found if you configure this environment variable : 
```
export RSNT_LOCAL_MODULEPATHS=/opt/software/easybuild/modules
``` 

Please test it out and let me know if it works.

**Comment by verdurin** [comment]
@mboisson that did seem to work, though I haven't yet checked whether the build has finished.

One thing I did notice is that there was a `signal 11` message eventually, each time I ran `proot`. Is that normal?

Will check the results of the build over the weekend and report back.

**Comment by mboisson** [comment]
Mmm, it's possible that proot messes with the build process. It remaps all calls to specific path to another path. It is known to be much slower than a regular session. It really is meant for testing, not for production.

**Comment by verdurin** [comment]
Here's what I tried:
```
eb --force --installpath /opt/software/easybuild SCOTCH-6.0.9-gompi-2019b.eb -dr
```
and here are the logs:
```
== processing EasyBuild easyconfig /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-GCC-8.3.0.eb
== building and installing avx512/Compiler/gcc8/openmpi/3.1.4...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 25 min 30 sec)
== Results of the build can be found in the log file(s) /opt/software/easybuild/software/2017/avx512/Compiler/gcc8/openmpi/3.1.4/ea
sybuild/easybuild-OpenMPI-3.1.4-20200528.195909.log
== processing EasyBuild easyconfig /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/g/gompi/gompi-2019b.eb
== building and installing Core/gompi/.2019b...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/user01/avx512/gompi/2019b/system-system): build failed (first 3
00 chars): Module command 'module load openmpi/3.1.4' failed with exit code 1; stderr: Lmod has detected the following error: These
 module(s) or extension(s) exist but cannot be loaded as requested: "openmpi/3.1.4"
   Try: "module spider openmpi/3.1.4" to see how to load the module(s).



; stdout: _mlstatus = (took 8 min 11 sec)
== Results of the build can be found in the log file(s) /tmp/eb-jqurF5/easybuild-gompi-2019b-20200528.195909.ewkjt.log
```

**Comment by mboisson** [comment]
Are you able to load the `openmpi/3.1.4` manually after loading the `gcc/8.3.0` module ? 
What is the value of `$MODULEPATH` after loading the `gcc/8.3.0` module when you have 
```
export RSNT_LOCAL_MODULEPATHS=/opt/software/easybuild/modules
``` 

set ?

**Comment by mboisson** [comment]
Actually, I could reproduce. I will investigate.

**Comment by mboisson** [comment]
Mmm, actually, I can't reproduce it : 
```[mboisson@cvmfs-client-dev ~]$ export RSNT_LOCAL_MODULEPATHS=/opt/software/easybuild/modules; eb --force --installpath /opt/software/easybuild SCOTCH-6.0.9-gompi-2019b.eb -dr
== temporary log file in case of crash /tmp/eb-aG9nWg/easybuild-kdR2k8.log
== Running parse hook for SCOTCH-6.0.9-gompi-2019b.eb...
== Running parse hook for gompi-2019b.eb...
== Running parse hook for GCC-8.3.0.eb...
== Running parse hook for GCCcore-8.3.0.eb...
== Running parse hook for OpenMPI-3.1.4-GCC-8.3.0.eb...
== Running parse hook for GCC-8.3.0.eb...
== Running parse hook for GCC-8.3.0.eb...
== Running parse hook for GCCcore-8.3.0.eb...
== Running parse hook for hwloc-1.11.12-GCCcore-8.3.0.eb...
== Running parse hook for GCCcore-8.3.0.eb...
== Running parse hook for GCCcore-8.3.0.eb...
== Running parse hook for numactl-2.0.12-GCCcore-8.3.0.eb...
== Running parse hook for libpciaccess-0.14-GCCcore-8.3.0.eb...
== Running parse hook for xorg-macros-1.19.2-GCCcore-8.3.0.eb...
== Running parse hook for gompi-2019b.eb...
== resolving dependencies ...
== Running parse hook for OpenMPI-3.1.4-GCC-8.3.0.eb...
== Running parse hook for hwloc-1.11.12-GCCcore-8.3.0.eb...
== processing EasyBuild easyconfig /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/h/hwloc/hwloc-1.11.12-GCCcore-8.3.0.eb
== building and installing Core/hwloc/1.11.12...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 2 min 42 sec)
== Results of the build can be found in the log file(s) /opt/software/easybuild/software/2017/Core/hwloc/1.11.12/easybuild/easybuild-hwloc-1.11.12-20200602.014345.log
== processing EasyBuild easyconfig /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-GCC-8.3.0.eb
== building and installing avx2/Compiler/gcc8/openmpi/3.1.4...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...

== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 31 min 12 sec)
== Results of the build can be found in the log file(s) /opt/software/easybuild/software/2017/avx2/Compiler/gcc8/openmpi/3.1.4/easybuild/easybuild-OpenMPI-3.1.4-20200602.021458.log
== processing EasyBuild easyconfig /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/g/gompi/gompi-2019b.eb
== building and installing Core/gompi/.2019b...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 55 sec)
== Results of the build can be found in the log file(s) /opt/software/easybuild/software/2017/Core/gompi/.2019b/easybuild/easybuild-gompi-2019b-20200602.021553.log
== processing EasyBuild easyconfig /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.9-gompi-2019b.eb
== building and installing avx2/MPI/gcc8/openmpi3.1/scotch/6.0.9...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 3 min 17 sec)
== Results of the build can be found in the log file(s) /opt/software/easybuild/software/2017/avx2/MPI/gcc8/openmpi3.1/scotch/6.0.9/easybuild/easybuild-SCOTCH-6.0.9-20200602.021911.log
== Build succeeded for 4 out of 4
== Temporary log file(s) /tmp/eb-aG9nWg/easybuild-kdR2k8.log* have been removed.
== Temporary directory /tmp/eb-aG9nWg has been removed.```

**Comment by verdurin** [comment]
Okay, will try it. The original instructions made it look as if you only needed to set that variable after the module building, or at least I interpreted them that way.

**Comment by verdurin** [comment]
After loading `gcc/8.3.0` this is the value of `$MODULEPATH`:
```
/cvmfs/soft.computecanada.ca/easybuild/modules/2017/avx512/Compiler/gcc8:/home/user01/.local/easybuild/modules/2017/Core:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/Core:/cvmfs/soft.computecanada.ca/custom/modules
```

Still seeing the same error when I build with `RSNT..` set:
```
== Running parse hook for GCC-8.3.0.eb...
== Running parse hook for GCC-8.3.0.eb...
== Running parse hook for GCCcore-8.3.0.eb...
== Running parse hook for hwloc-1.11.12-GCCcore-8.3.0.eb...
== Running parse hook for GCCcore-8.3.0.eb...
== Running parse hook for GCCcore-8.3.0.eb...
== Running parse hook for numactl-2.0.12-GCCcore-8.3.0.eb...
== Running parse hook for libpciaccess-0.14-GCCcore-8.3.0.eb...
== Running parse hook for xorg-macros-1.19.2-GCCcore-8.3.0.eb...
== Running parse hook for gompi-2019b.eb...
== resolving dependencies ...
== processing EasyBuild easyconfig /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/g/gompi/gompi-2019b.eb
== building and installing Core/gompi/.2019b...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/user01/avx512/gompi/2019b/system-system): build failed (first 300 chars): Module command 'module load openmpi/3.1.4' failed with exit code 1; stderr: Lmod has detected the following error: These module(s) or extension(s) exist but cannot be loaded as requested: "openmpi/3.1.4"
   Try: "module spider openmpi/3.1.4" to see how to load the module(s).



; stdout: _mlstatus = (took 32 sec)
== Results of the build can be found in the log file(s) /tmp/eb-vA7efw/easybuild-gompi-2019b-20200602.094926.fCutc.log
ERROR: Build of /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/g/gompi/gompi-2019b.eb failed (err: 'build failed (first 300 chars): Module command \'module load openmpi/3.1.4\' failed with exit code 1; stderr: Lmod has detected the following error: These module(s) or extension(s) exist but cannot be loaded as requested: "openmpi/3.1.4"\n   Try: "module spider openmpi/3.1.4" to see how to load the module(s).\n\n\n\n; stdout: _mlstatus =')
```

**Comment by mboisson** [comment]
Mmm, something isn't right. Is this run within the `proot` shell as instructed in https://github.com/ComputeCanada/software-stack/issues/11#issuecomment-634990532 ?

Do you see the file `/cvmfs/soft.computecanada.ca/config/lmod/SitePackage_localpaths.lua`  in that shell ?

**Comment by verdurin** [comment]
Yes, it's in the same shell. Could the signal 11 errors be implicated?

That isn't visible in the shell.

**Comment by verdurin** [comment]
Just tried again from the `proot` step and the result is the same.

`soft-dev` is mounted.

**Comment by mboisson** [comment]
That's weird. It is possible it is caused by `proot` I guess. I tried it via a special node that has a "funky" CVMFS configuration by which `soft-dev.computecanada.ca` is always mounted in the location of `soft.computecanada.ca`. This requires manual CVMFS mounts, rather than relying on automatic configuration. I think I will deploy the changes to production today, as they are anyway harmless unless the environment variable `RSNT_LOCAL_MODULEPATHS` is defined.

**Comment by mboisson** [comment]
Oh, you could also try this instead of the `proot` business. 

1) Clone https://github.com/ComputeCanada/software-stack-config/
2) Checkout the branch `local_module_paths` 
3) Define the `LMOD_PACKAGE_PATH` environment variable to point to the `lmod` folder in the resulting repository.

**Comment by verdurin** [comment]
Yes, that works for building the module.

However, even though the `RSNT...` variable is set, that path is not in `$MODULEPATH` so without further manual action I can't see the modules I've built.

**Comment by ofisette** [comment]
I tested this on our local cluster using `proot`, with one and then with two additional module trees that were built by installing packages with `eb`. Everything seems to work properly. I was able to add new modules for custom versions, and to shadow existing modules from the main RSNT tree.

**Comment by ofisette** [comment]
I found a bug with how architectures are handled. It seems that arch-specific module paths are not added properly. For instance:

```
$ proot -b /cvmfs/soft-dev.computecanada.ca:/cvmfs/soft.computecanada.ca env -i CC_CLUSTER=$CC_CLUSTER TERM=$TERM HOME=$HOME RSNT_LOCAL_MODULEPATHS=/opt/software/repo2/modules bash -l
$ module load gcc/7.3.0
[...]
$ echo $MODULEPATH 
/opt/software/modulefiles:/opt/software/repo2/modules/2017/avx/Compiler/gcc7.3:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/avx/Compiler/gcc7.3:/opt/software/repo2/modules/2017/Core:/home/olf067/.local/easybuild/modules/2017/Core:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/Core:/cvmfs/soft.computecanada.ca/custom/modules
$ module load arch/avx2
[...]
$ module load gcc/7.3.0
[...]
$ echo $MODULEPATH 
/opt/software/modulefiles:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/avx2/MPI/gcc7.3/openmpi2.1:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/avx2/Compiler/gcc7.3:/opt/software/repo2/modules/2017/Core:/home/olf067/.local/easybuild/modules/2017/Core:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/Core-avx2:/cvmfs/soft.computecanada.ca/custom/modules-avx2:/opt/software/repo2/modules/2017/avx/Compiler/gcc7.3:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/avx/Compiler/gcc7.3:/cvmfs/soft.computecanada.ca/custom/modules
```
I was expecting `/opt/software/repo2/modules/2017/avx/Compiler/gcc7.3` to be replaced by `/opt/software/repo2/modules/2017/avx2/Compiler/gcc7.3`, but it remained unchanged. (I do have modules in the latter directory. If I had none, I would have expected that directory to be removed from `MODULEPATH`.)

**Comment by mboisson** [comment]
> Yes, that works for building the module.
> 
> However, even though the `RSNT...` variable is set, that path is not in `$MODULEPATH` so without further manual action I can't see the modules I've built.

@verdurin Did you reload modules after setting the `RSNT...` variable ? The local path should be added to MODULEPATH after you reload the compiler/mpi modules.

**Comment by mboisson** [comment]
@ofisette mmm, this will take some testing. The `arch` modules are a bit special...

**Comment by mboisson** [comment]
@verdurin, @ofisette, this has been pushed to production. Can you test without the `proot` or local clone of the repository business ? It should just work now. 

Note that I have yet to look at the problem with the `arch` modules.

**Comment by ofisette** [comment]
@mboisson It still works, now simply by exporting `RNST_LOCAL_MODULEPATHS`.

**Comment by mboisson** [comment]
Can you give me the steps to reproduce the `arch` issue ?

**Comment by ofisette** [comment]
On an AVX cluster:

```
mkdir /opt/software/repo2
RSNT_ARCH=avx2 eb --force --installpath /opt/software/repo2 BCFtools-1.9-GCC-7.3.0.eb
export RSNT_LOCAL_MODULEPATHS=/opt/software/repo2/modules
module load arch/avx2
module load gcc/7.3.0
echo $MODULEPATH
```

This does not add `/opt/software/repo2/modules/2017/avx2/Compiler/gcc7.3` to `MODULEPATH` but it should.

If I do instead from a fresh session:

``
eb --force --installpath /opt/software/repo2 BCFtools-1.9-GCC-7.3.0.eb
export RSNT_LOCAL_MODULEPATHS=/opt/software/repo2/modules
module load gcc/7.3.0
echo $MODULEPATH
```
Then `MODULEPATH` contains `/opt/software/repo2/modules/2017/avx/Compiler/gcc7.3` as it should. But if play with the arch (`module load arch/avx2; module load arch/avx`), then that directory gets removed and not added back.

So I think something is missing from the `arch` modules.

Just as an idea, I use the following to shadow `arch/avx2` on our local cluster:

```
if (mode() ~= "spider") then
	prepend_path("MODULEPATH","/cvmfs/soft.computecanada.ca/custom/modules-avx2")
	prepend_path("MODULEPATH","/opt/software/modulefiles-avx2")
end
```

Replacing the current `/cvmfs/soft.computecanada.ca/custom/modules/arch/avx2.lua`:

```
prepend_path("MODULEPATH","/cvmfs/soft.computecanada.ca/custom/modules-avx2")
```

That is probably not a clean solution, though. (Also, that specific custom module was not present during any of my tests.)

**Comment by mboisson** [comment]
Ok, @ofisette, this is fixed by this commit : https://github.com/ComputeCanada/software-stack-config/commit/7b3038f66e6626a001c90fe110626da9820c5286

Can you confirm locally, and I can push to prod on Monday (read-only Friday)

**Comment by ofisette** [comment]
This fixed the issue with the missing paths for the new architecture. Unfortunately, it introduced a new bug: the existing paths for the previously-loaded architecture are not unset. That is to say:

```
$ proot_and_add_to_RSNT_LOCAL_MODULES /opt/software/repo2
$ what_is_in_MODULEPATH_regarding_repo2
/opt/software/repo2/modules/2017/Core
$ module load gcc/7.3.0
$ what_is_in_MODULEPATH_regarding_repo2
/opt/software/repo2/modules/2017/avx/Compiler/gcc7.3:/opt/software/repo2/modules/2017/Core
$ module load arch/avx2
$ what_is_in_MODULEPATH_regarding_repo2
/opt/software/repo2/modules/2017/Core:/opt/software/repo2/modules/2017/avx/Compiler/gcc7.3
$ module load gcc/7.3.0
$ what_is_in_MODULEPATH_regarding_repo2
/opt/software/repo2/modules/2017/avx2/Compiler/gcc7.3:/opt/software/repo2/modules/2017/Core:/opt/software/repo2/modules/2017/avx/Compiler/gcc7.3
```

Loading an `arch` module needs to purge everything arch-related and that is not happening.

**Comment by mboisson** [comment]
@ofisette, I think your local path behaves exactly like our central ones. I think that the `arch` modules trigger a reload of too many modules (both `nixpkgs` and `StdEnv` which itself reloads `nixpkgs`, and the compilers), and this causes the issue you see.

**Comment by ofisette** [comment]
@mboisson You are right. Testing this *without* `RSNT_LOCAL_MODULES`, I can reproduce the issue if I load many toolchain modules before switching `arch`; it seems that LMod eventually gets confused and no longer unsets paths properly.

Interestingly, a simple workaround is to `module purge` before switching `arch`. I am fine with recommending that to users. I suppose fixing LMod would be non-trivial.

**Comment by mboisson** [comment]
Maybe not that hard. When I designed those modules, I was trying to get StdEnv to switch version (from 2016 to 2018) when loading arch/avx512 module, but I don't think it ever worked properly. If I remove some module files related to this, I think it fixes it. I will deploy something to dev, and I would appreciate some testing on your part.

**Comment by ofisette** [comment]
That last change did the trick! I tested both the central RSNT repo and a custom one with `RSNT_LOCAL_MODULES`, and both behave as expected, i.e. replacing all `avx` paths by `avx2`.

**Comment by mboisson** [comment]
Ok. I have deployed this to production. @verdurin, please let me know if you encounter further issues.

**Comment by mboisson** [comment]
I am going to mark this one as closed. Feel free to reopen it if you encounter issues.

**Comment by verdurin** [comment]
@mboisson apologies for not being able to test before.
Tried it just now and I still can't see the local path in `$MODULEPATH` even when I use exactly the commands Olivier listed on 4th June and ensure I reload the `gcc` module.

This is on an older cluster, in case it makes any difference, without using `proot` or the custom repository, or mounting the `dev` `CVMFS` repo.

**Comment by mboisson** [comment]
Can you give me the exact commands to reproduce from a fresh shell ?
  

  
Maxime
  

  
  
  

  
  
>

**Comment by verdurin** [comment]
```
[user01@login1 ~]$ export RSNT_LOCAL_MODULEPATHS=/opt/software/easybuild/modules/all
[user01@login1 ~]$ module load gcc/7.3.0
[user01@login1 ~]$ echo $MODULEPATH
/cvmfs/soft.computecanada.ca/easybuild/modules/2017/avx512/MPI/gcc7.3/openmpi3.1:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/avx512/Compiler/gcc7.3:/home/user01/.local/easybuild/modules/2017/Core:/cvmfs/soft.computecanada.ca/easybuild/modules/2017/Core:/cvmfs/soft.computecanada.ca/custom/modules
```

This is when I've already built the new module with:
```
eb --force --installpath /opt/software/easybuild BCFtools-1.9-GCC-7.3.0.eb
```

**Comment by ofisette** [comment]
I wonder why `all` is in the module path with:

```
export RSNT_LOCAL_MODULEPATHS=/opt/software/easybuild/modules/all
```

I think this should rather be:

```
export RSNT_LOCAL_MODULEPATHS=/opt/software/easybuild/modules/
```

**Comment by verdurin** [comment]
@ofisette yes, my habits let me down here (we don't use HMNS with EB).

With that change it does work.

**Comment by mboisson** [comment]
@verdurin good. And thanks @ofisette for finding the issue.
